### ISSUE TITLE
Changing the lockscreen type breaks the OS

### ISSUE THREAD

**Issue by Parker0312** [mrhaydendp/Fire-Tools#51]
So I changed the lock screen from pin to pattern and doing so cause it so whenever I turned on my tablet, (fire 7 12th generation), the lock screen was a black void that I could not get past with nothing but the battery, and time at the top were it usually is, flickering. Visible, not visible, visible, not visible. **It does not brick the tablet** so I could do a **hard reset**, I had no important data and all my google stuff was on the cloud so it was fine but was irritating because everything I did with fire toolbox before had to be redone. I also wanted to briefly mention the screen recording issue. When using the screen capture feature, fir toolbox either crashes, or just simply does not save the video to the folder I selected it to.

**Comment by mrhaydendp** [comment]
Thanks for letting me know! I don't use a password on my test device so I didn't catch this. Let me do some testing and see if I can fix the issue.

**Comment by mrhaydendp** [comment]
Sorry for the misunderstanding, this isn't the same application as [Datastream33's Fire Toolbox](https://xdaforums.com/t/windows-linux-tool-fire-toolbox-v35-0.3889604/). Newer versions of FireOS don't support pattern and that's why it's hidden. Nonetheless, if you have ADB access you can create a new user and switch to that user:

``` shell
# Name it whatever you desire
adb shell pm create-user notlocked

# Use the id number in place of id
adb shell am switch-user id
```
